# Generated by Django 4.2.1 on 2023-05-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_artist_alter_record_price_alter_record_artist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="artist",
            new_name="artist_pk",
        ),
    ]
