# Generated by Django 4.2.1 on 2023-05-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album", models.CharField(max_length=125)),
                ("artist", models.CharField(max_length=125)),
                ("artwork", models.URLField(blank=True, max_length=300, null=True)),
                ("date", models.DateField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
