# Generated by Django 4.2.1 on 2023-06-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_record_owner_alter_record_price_artist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="artist",
            field=models.CharField(max_length=125),
        ),
    ]
