# Generated by Django 4.2.1 on 2023-05-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_rename_artist_record_artist_pk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="artist_pk",
            new_name="artist",
        ),
    ]
