# Generated by Django 4.2.1 on 2023-05-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0007_alter_record_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="artist",
            field=models.CharField(max_length=125),
        ),
    ]
