# Generated by Django 4.2.1 on 2023-05-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0009_alter_artist_artist_alter_record_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="album",
            field=models.CharField(max_length=125),
        ),
    ]
